### ISSUE TITLE
Unsupported file format for '.ruby-version'

### ISSUE THREAD

**Issue by looterz** [iam1980/metasploit-vps-installer#1]
Encountered an issue with the script on a fresh debian 8.5 box, this pops up and the rest fails to execute.

![terminal](http://i.imgur.com/tGpteh1.png)

Manually installing ruby-2.3.3 with rvm worked. A nice improvement to the script would be to add the metasploit-framework directory to the users path to avoid having to navigate inside.

**Comment by iam1980** [comment]
Seems like msf changed the .ruby-version format and it breaks rvm. fixed it. , thanks
